### ISSUE TITLE
Search through all workspaces

### ISSUE THREAD

**Issue by marcboscher** [lracicot/asana-tag-cleaner#1]
Getting the workspace ID is a real pain for a user.

The tool could instead iterate over all of the workspaces the user has access to, while still grouping similar tags only within individual workspaces.

Since the Asana node lib returns Bluebird promises, should be easy to parallelize the get of tags over all workspaces using Bluebird's map. 
http://bluebirdjs.com/docs/api/promise.map.html

Pseudo-js

```
asanaClient.getWorkspaces()
  .map(function (workspace) {
    return asanaClient.getTags(workspace);
  });
```

**Comment by lracicot** [comment]
Thank you marc! This issue has been addressed in c0a159bd9cb314c2638b54483ee6fd03605ea007
